# Generated by Django 5.2.2 on 2025-06-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_order_id_remove_orderupdate_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc_preview',
            field=models.CharField(default='', max_length=200),
        ),
    ]
